### ISSUE TITLE
Latest version breaks something - Timestamp?

### ISSUE THREAD

**Issue by KCastiglione** [jgh-/VideoCore#110]
I updated to latest HEAD VideoCore and it broke my setup like this:

https://github.com/arut/nginx-rtmp-module/issues/596

At first I thought it was something to do with nginx-rtmp, but downgrading to the previous version of VideoCore completely stopped the error.

With the latest VideoCore, timestamp  is 4:59:59 hours or so right at beginning or broadcast, but with previous version it starts correctly.

Screenshot from broadcast beginning:
![screen shot 2015-03-21 at 7 53 36 pm](https://cloud.githubusercontent.com/assets/96905/6767810/084e0f4e-d004-11e4-9a3e-147353a2fd23.png)

This is how the session is setup:

        _session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(720, 1280) frameRate:30 bitrate:1000000 useInterfaceOrientation:NO cameraState:VCCameraStateBack];
        [self.previewView addSubview:_session.previewView];
        [_session setUseAdaptiveBitrate:TRUE];
        _session.previewView.frame = self.previewView.bounds;
        _session.delegate = self;
        _session.orientationLocked = TRUE;

**Comment by jgh-** [comment]
I re-enabled b-frames in this version.  I've changed the CTS offset to a more correct value, give the latest HEAD a try.

**Comment by KCastiglione** [comment]
Still the same with the HEAD. Timestamp starts with at approximately 4:39:39

Podfile:

      platform :ios, '6.0'
      pod 'AFNetworking', '~> 2.5'
      pod 'VideoCore', :head


 $ pod update

       Update all pods
       Analyzing dependencies
       Downloading dependencies
       Using AFNetworking (2.5.1)
       Using UriParser-cpp (0.1.3)
       Installing VideoCore HEAD based on 0.3.0.2 (was HEAD based on 0.3.0.2)
       Using boost (1.51.0)
       Using glm (0.9.4.6)
       Generating Pods project
       Integrating client project



Screenshot:
![screen shot 2015-03-21 at 11 11 39 pm](https://cloud.githubusercontent.com/assets/96905/6768284/bac3cd10-d01f-11e4-8cd0-b4edd37641da.png)

**Comment by KCastiglione** [comment]
This is the version that works fine for me:

      pod 'VideoCore', '~> 0.3.0'

**Comment by jgh-** [comment]
Are you using VCSimpleSession or a custom graph?

**Comment by KCastiglione** [comment]
VCSimpleSession. width and height are changed (720, 1280), adaptive bitrate is TRUE, and orientationLocked is TRUE.


    _session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(720, 1280) frameRate:30 bitrate:1000000 useInterfaceOrientation:NO cameraState:VCCameraStateBack];
    [self.previewView addSubview:_session.previewView];
    [_session setUseAdaptiveBitrate:TRUE];
    _session.previewView.frame = self.previewView.bounds;
    _session.delegate = self;
    _session.orientationLocked = TRUE;

**Comment by KCastiglione** [comment]
VCSimpleSession right out of github has this problem. I just ran SampleBroadcaster from github with HEAD for VideoCore and broadcast started at around 04:39:37.

**Comment by jgh-** [comment]
OK I've made a couple of changes and put out a 0.3.0.3 ... Testing with nginx-rtmp seems to give correct results (I am not seeing the errors you listed, nor am I seeing incorrect timestamps)

**Comment by KCastiglione** [comment]
The latest HEAD looks like it has fixed it. Thanks for fixing it. Can you share what was wrong?

**Comment by KCastiglione** [comment]
Trying it now.

**Comment by jgh-** [comment]
I added a start() command to the mixers in 0.3.0 so they wont begin
generating timestamps until it is called.  What was happening though was
the timestamp epoch was being set on connect even though there were sample
buffers in flight with later timestamps, meaning that we would end up with
non-monotonic timestamps briefly and this caused a big freak out.  The
solution is to set the epoch before the mixer start is called, even if it
is minutes before the connection is started because rtmp allows an
arbitrary first timestamp

**Comment by KCastiglione** [comment]
Great thanks. It looks fixed now. Thanks again for the fixing the problem! Will report if it surfaces again.

**Comment by omarojo** [comment]
Sorry I dont know if its correct to reOpen this issue. Im getting this same problems about the 4:39:37 timestamp when streaming to Facebook Live endpoints. And Im using 0.3.2 where the issue should have already been solved. @jgh-
