### ISSUE TITLE
ctsOffset causes weird behaviour with hls on nginx-rtmp-module

### ISSUE THREAD

**Issue by hannseman** [jgh-/VideoCore#116]
First of all thanks for a great library! 

I'm streaming to an nginx-server with nginx-rtmp-module enabled where the stream is consumed over hls. All pod versions later than `0.1.12` causes the first hls-segment to get a duration of `204963823041217` seconds:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:204963823041217
#EXT-X-PLAYLIST-TYPE: EVENT
#EXT-X-DISCONTINUITY
#EXTINF:204963823041217.219,
0.ts
#EXTINF:10.033,
1.ts
```
It appears like the initial timestamp is wrong. This behaviour was introduced in ec5ecee4104930de4d0d8f45bb25fe6bd97cb38b. If I remove the ctsOffset `2000/self.fps` when initializing `H264Packetizer` the playlist looks normal again but I'm not sure I fully understand the meaning of the offset. This is on `0.3.0.3`.

**Comment by hannseman** [comment]
This appears to have been fixed by `658ae6709245fd59fd11f1d54bc77d068917aa50`:+1:

**Comment by hannseman** [comment]
I might have been too quick here. Still getting weird timestamps.

**Comment by jgh-** [comment]
Does this happen consistently or is it something that happens randomly and infrequently?

**Comment by hannseman** [comment]
It happens consistently. I create a `VCSimpleSession` with these arguments:

```
[[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(640, 360)
                                frameRate:25
                                  bitrate:1000000
                  useInterfaceOrientation:NO
                              cameraState:VCCameraStateBack
                              aspectMode:VCAscpectModeFill];
```

**Comment by hannseman** [comment]
Actually it works the first time running `startRtmpSessionWithURL` but when running it a second time after having run `endRtmpSession` it's producing these weird playlists. Note that I'm running on the same  `VCSimpleSession` instance. Should that be working or do I need to create a new session instance before each `startRtmpSessionWithURL`?

**Comment by jgh-** [comment]
ok, that might mean that the timestamps aren't correctly resetting or something.

**Comment by hannseman** [comment]
Hmm now I'm getting it all the time. The only way to get it to produce normal playlists is to remove the pod from the Podfile and uninstall VideoCore and then add it again and let run pod install. Then it will produce a normal playlist for the first session. All subsequent rtmp sessions will have weird timestamps. Does not matter how many times I rebuild or clean the project. Really weird..

**Comment by hannseman** [comment]
If I force usage of `videocore::iOS::H264Encode` instead of `videocore::Apple::H264Encode` it always works.

**Comment by jgh-** [comment]
What if you turn off Main profile (You can do this by setting the last
parameter to 'true' for Apple::H264Encode)

**Comment by hannseman** [comment]
Yes I've tried that but no difference. I've submitted a pull request where the CTS offset is also applied to the PTS in `H264Encode` and this appears to have fixed the issue.

**Comment by KCastiglione** [comment]
@jgh-  could you please make a new release with this fix, to get the updates through Pod. thank you.
