### ISSUE TITLE
add VideoCore as a submodule in my app

### ISSUE THREAD

**Issue by notedit** [jgh-/VideoCore#12]
hi  james:

i am using VideoCore as a submodule in my project, i setup the search path just like  SampleBroadcaster sample.

but after the setup, xcode told me there are two errors, 

one is  "/Users/xiang/Work/kaiboapp/kaibo/videocore/rtmp/RTMPSession.cpp:22:10: 'videocore/rtmp/RTMPSession.h' file not found"

another is  "/Users/xiang/Work/kaiboapp/kaibo/videocore/sources/iOS/CameraSource.mm:23:10: 'videocore/sources/iOS/CameraSource.h' file not found" 

how i can setup videocore properly？

**Comment by ravigautam7786** [comment]
Hi James,

I am using videocore library but I am not able to run the code. I followed the these steps.

1- I downloaded the code via cocoa pods.
2- Then I import public,boost folder into my project.

But There is many errors says like  #include <videocore/sources/iOS/GLESUtil.h> file not found

What I do in this case.

And I see all the file included in that pattern.

Can you please let me know how I will this library in my existing project.

Regards
Ravi

**Comment by jgh-** [comment]
You need to open the .xcworkspace file that Cocoapods creates.

**Comment by ravigautam7786** [comment]
But I want to integrate this feature in my existing project. Then how I will do that?
Thanks

**Comment by jgh-** [comment]
Cocoapods creates a workspace with your existing project and a Cocoapods
project.  I recommend checking the cocoapods documentation on how to use it.

**Comment by JALsnipe** [comment]
https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by ravigautam7786** [comment]
Ok, but if I want to use this without cocoa pods then its possible. I want to really use this amazing library.

**Comment by ravigautam7786** [comment]
Please let me know.
Thanks

**Comment by ravigautam7786** [comment]
Please let me know how I will use it in my existing project without cocoa pods.

**Comment by ravigautam7786** [comment]
I given the header search path to $(SRCROOT) now videocore errors removed but now I have boost file not found like "#include <boost/tokenizer.hpp>
"

**Comment by ravigautam7786** [comment]
Hi,

I want to change video size at runtime while streaming video but I am able to do that. Please let me know how I can change video size at run time.

Thanks
Ravi

**Comment by chiragIOS** [comment]
@ravigautam7786  have you found the way videocore use without cocoapods ? if yes please let me know
