### ISSUE TITLE
Basic example for filters with VCSimpleSession

### ISSUE THREAD

**Issue by KCastiglione** [jgh-/VideoCore#121]
Hi,
it will be great if there is an example with VCSimpleSession on how to use filters.

**Comment by JALsnipe** [comment]
There is no way to dynamically change the filter of a `VCSimpleSession` instance at this time.  To test out filters, you can change line 689 of `VCSimpleSession.mm` and init a new session.
```obj-c
m_videoMixer->setSourceFilter(m_cameraSource, dynamic_cast<videocore::IVideoFilter*>(m_videoMixer->filterFactory().filter("com.videocore.filters.grayscale"))); // default is com.videocore.filters.bgra
```
