### ISSUE TITLE
Passing data to startRtmpSessionWithURL in VCSimpleSession

### ISSUE THREAD

**Issue by KCastiglione** [jgh-/VideoCore#124]
What is the best way to  pass custom data [for example username session info] to startRtmpSessionWithURL?

**Comment by jgh-** [comment]
Currently usernames and such aren't supported by the RTMP stack.  I'll have to take a look at how to implement that.

**Comment by bintu1234** [comment]
now i am facing same issue that in rtmp url i want give the username so is it now working in video core

**Comment by bintu1234** [comment]
@KCastiglione  is passing data working now can you please help me out for the rtmp url as rtmp://severname.tv/server/userID/streamID but my session is not starting so where is the issue

**Comment by JALsnipe** [comment]
@bintu1234 stop spamming your question on every issue.

**Comment by bintu1234** [comment]
@JALsnipe  sorry for that but i don't have other resource but i didn't ask same question on every issue what ever sorry
