### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jgh-/VideoCore#138]
I would like to point out that identifiers like "[`__videocore__FilterFactory__`](https://github.com/jgh-/VideoCore/blob/42788de484ddf830f0292e2bc24359737dac24e3/filters/FilterFactory.h#L3)" and "[`__videocore_util_h`](https://github.com/jgh-/VideoCore/blob/1b30af896d328cd5fb41b2dac24be846969552d9/system/util.h#L26)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jgh-** [comment]
@elfring thank you for pointing this out.  I will adjust the naming for the header files.

Two things though:

1. Please don't be so condescending when leaving these messages in peoples' repos.  Perhaps change your question to "Could you change the unique names?" 

2. The identifiers such as __videocore__FilterFactor__ are actually generated by Xcode when creating a C++ implementation/header file pair.  File a bug report with Apple.

**Comment by elfring** [comment]
Is it better to keep this issue open until the affected implementation details will be fixed?

**Comment by jgh-** [comment]
No
