### ISSUE TITLE
Camera View is black on Iphone 6

### ISSUE THREAD

**Issue by zohaibkhanniazi** [jgh-/VideoCore#171]
On iphone 6 Cameraview is black nothing to show. on other devices it is working fine

**Comment by JALsnipe** [comment]
Anything in the log?  Are you using a custom filter?  The sample project?

**Comment by zohaibkhanniazi** [comment]
yup i am using sample project.

**Comment by zohaibkhanniazi** [comment]
not change anything in sample project. its working fine on all other devices except iphone6

**Comment by zohaibkhanniazi** [comment]
It was due to issue in my mobile. I have just tested on my another iphone 6 and its working great.

**Comment by IOSDeveloperProgrammer** [comment]
@zohaibkhanniazi  @zohaibkhanniazi  @jgh-  Hi, I am having same problem. After open, camera delay for 10 - 30sec when i was click connect button   How to reduce delay camera ? Did you find any solutions ?? can you please help me on this issue.

Thank you.
