### ISSUE TITLE
Youtube live streaming

### ISSUE THREAD

**Issue by zohaibkhanniazi** [jgh-/VideoCore#172]
Is this sample will work for youtube live stream.
if yes than how can we put username and password in url

**Comment by JALsnipe** [comment]
VideoCore does work with YouTube, but you need to integrate with the live streaming APIs first.  For YouTube support, use the [youtube-livestreaming-api](http://stackoverflow.com/?tags=youtube-livestreaming-api) or [youtube-api](http://stackoverflow.com/?tags=youtube-api) tags on StackOverflow.

**Comment by zohaibkhanniazi** [comment]
Is youtube live stream api available for ios?
I searched it but never find anyhelp about ios
https://developers.google.com/youtube/v3/live/code_samples/

**Comment by jgh-** [comment]
They have a REST api that's a total pain to use, but it can be done.
