### ISSUE TITLE
does not use video mixer and use VideoCore in background

### ISSUE THREAD

**Issue by notedit** [jgh-/VideoCore#179]
hi  @jgh- 

i  am using videocore to stream my iOS Screen data,  i found that the video mixer use opengles, so it can not be used in background,

what if i just have one  video source（ios screen data),  so i do not need to use video mixer, so i can run videocore in backgroud.  is that possible?

**Comment by toss156** [comment]
yes, is possible .  Just modify the method  GLESVideoMixer::pushBuffer  ,  use memcpy to set the screen data in m_pixelBuffer

**Comment by jgh-** [comment]
Alternatively you can just take the mixer out of the equation if you have a source that provides reliable timestamps to the RTMP session (the metadata object passed to the encoder should have the timestamp as a double in Milliseconds)

**Comment by KCastiglione** [comment]
@notedit @jgh- how does screen capture work with VideoCore? is it possible to add an example? thank you!

**Comment by jgh-** [comment]
if you're doing screen capture in the background you will almost certainly not get into the app store (see Shou, iRec, others who are on alternative app stores / don't work on iOS 9)

**Comment by rgerovski** [comment]
@jgh- Could you provide a simple example of streaming a screen capture with VideoCore?
