### ISSUE TITLE
VCSimpleSession.h not found

### ISSUE THREAD

**Issue by RobertSmart** [jgh-/VideoCore#184]
When I install this using cocoa pods with the use_frameworks! flag set, I get an error that it cannot fin the VCSimpleSession.h file in my bridging header.

However the use_frameworks! flag is suppose to mean that you do not need the bridging header, but I cannot get it to work with out it either.

Has anyone successfully used VideoCore in Swift using cocoa pods with use_frameworks flag set?

Thanks

**Comment by RobertSmart** [comment]
Was trying to use cocoa pods with the use_frameworks flag, which is not suitable for this project.

**Comment by aramikg** [comment]
is there a way around this?  What if you have other pods that use_frameworks?

**Comment by sleekuser** [comment]
have you tried placing `Pods/VideoCore/api/iOS/**` in `User Header Search Paths`?

**Comment by Craytor** [comment]
@sleekuser @aramikg 

@sleekuser's answer works if you have to have use_frameworks! in your podfile.

**Comment by ZenonHuang** [comment]
@sleekuser  thank your answer

**Comment by orenk86** [comment]
This issue started showing up for me even without the use_frameworks flag.
Also regardless, I've had major issues with the code completion in XCode ever since I installed this library.
@sleekuser 's answer solved both issues for me. Thanks!!!
