### ISSUE TITLE
Streaming in background

### ISSUE THREAD

**Issue by sobytes** [jgh-/VideoCore#185]
Hi All,

Will you be adding functionality to allow streaming in background mode so you can close the app and it will continue to stream?

Thanks

**Comment by JALsnipe** [comment]
There's no way apple would approve and app that streams in the background, but even if they did, it would be impossible to run encoding calls in the background, as the iOS runtime will kill your app if you try to run any OpenGL calls while your app is backgrounded.

**Comment by sobytes** [comment]
Ok that's a big no then thanks

**Comment by toss156** [comment]
You can keep the steams in the background by using background mode (VOIP) , try to add code in the function :  StearmSession::connet

CFReadStreamSetProperty(readStream, kCFStreamPropertyShouldCloseNativeSocket, kCFBooleanFalse);
                CFWriteStreamSetProperty(writeStream, kCFStreamPropertyShouldCloseNativeSocket, kCFBooleanFalse);
                CFReadStreamSetProperty(readStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP);
                CFWriteStreamSetProperty(writeStream, kCFStreamNetworkServiceType, kCFStreamNetworkServiceTypeVoIP
                                         );

**Comment by JALsnipe** [comment]
Yes but you shouldn't be able to keep access to the camera this way.

**Comment by toss156** [comment]
yes，camera is not accessible in background， but screen recorder is ok

**Comment by jgh-** [comment]
If you guys are going to be making modifications to stream in the background, or indeed modifications at all please give back to the project with a pull request.
