### ISSUE TITLE
Pod install issue.

### ISSUE THREAD

**Issue by tapfreaks** [jgh-/VideoCore#187]
Hi James,

Hopefully you are doing good, I was trying your VideoCore project unfortunately pod install is not working for SampleBrodcast project because some missing "boost" project link.

I would be thankful if you can fix this.

Also I got few questions, actually I am looking to play & publish rtmp streams to red5 server, do this project cover this all ?

Thanks,
Asif

**Comment by jgh-** [comment]
There are compatibility issues with Red5.  See #186 for discussion about the cocoapods.
