### ISSUE TITLE
Xcode 7 dyld: Symbol not found: ___NSDictionary0__ error

### ISSUE THREAD

**Issue by sleekuser** [jgh-/VideoCore#196]
I am receiving this error while using cocoapods and swift

`dyld: Symbol not found: ___NSDictionary0__
  Referenced from: ~/Library/Developer/Xcode/DerivedData/__-hfeyxqwmochgbzfmdhxoecpsiplh/Build/Products/Debug-iphonesimulator/videocore.framework/videocore (which was built for iOS 9.0)
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.4.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in ~/Library/Developer/Xcode/DerivedData/__-hfeyxqwmochgbzfmdhxoecpsiplh/Build/Products/Debug-iphonesimulator/videocore.framework/videocore
(lldb)`

**Comment by jgh-** [comment]
I don't think VideoCore will work particularly well (or at all) with the
simulator.

**Comment by sleekuser** [comment]
I didn't use `VCSimpleSession` at all while doing integration with cocoapods. It didn't work on a regular device either.

I don't think this is VideoCore specific error. I disintegrated cocoapods and used `pod install` to fix the problem. Closing this issue now.
