### ISSUE TITLE
GLM Include Error

### ISSUE THREAD

**Issue by Craytor** [jgh-/VideoCore#209]
Hello, I'm fairly new to using pods. I'm currently getting the following error,
![screen shot on 2015-10-13 at 20_29_39](https://cloud.githubusercontent.com/assets/3680866/10472013/8284e152-71e9-11e5-8b35-76b2a4cda957.png)
it has to do with this `#include "type_half.inl"` more specifically not being found.

I'm not sure what to do, any help would be appreciated. I don't know if this is connected at all, but I have an error when doing `pod install`, which is this:
<img width="727" alt="screen shot on 2015-10-13 at 20_33_18" src="https://cloud.githubusercontent.com/assets/3680866/10472029/be3f6d3e-71e9-11e5-83bd-c3f60517d664.png">

Thanks!

**Comment by andwun** [comment]
This seems to be a ridiculous incompatibility introduced with cocoapods v0.39.0.
Downgrading back to v0.38.2 got working again for me for now.

**Comment by Craytor** [comment]
How do you downgrade back to v0.38.2? I'm fairly new to this.

Thanks!

**Comment by andwun** [comment]
This worked for me:

> gem install cocoapods -v 0.38.2
> gem uninstall cocoapods -v 0.39.0

**Comment by Craytor** [comment]
Right, so I did that, and now I get this ugly mess.
![screen shot 2015-10-14 at 9 15 26 am](https://cloud.githubusercontent.com/assets/3680866/10484622/1f82255e-7254-11e5-98ce-6bb1283a5ff0.png)
 
Am I doing something wrong?

**Comment by andwun** [comment]
Well, all the middle part (lines 2 to 10) is just the update notification. Ignore that for now.
However, I think you cut off the interesting part below "Unable to satisfy the following requirements:"
Please post whats below there + your Podfile.

**Comment by Craytor** [comment]
![screen shot 2015-10-14 at 9 14 45 am](https://cloud.githubusercontent.com/assets/3680866/10484726/b715ea4a-7254-11e5-9dc5-c73e3759ea70.png)

Pod file:
```
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

# See: http://guides.cocoapods.org/making/making-a-cocoapod.html#release
# Once the pod has been released, use a version number here instead of a path.
#pod 'VideoCore', '~>0.3.0.3'
pod 'VideoCore', path: '../..'

```

**Comment by Craytor** [comment]
I fixed it by uncommenting the first VideoCore line, and commenting the second.
```
pod 'VideoCore', '~>0.3.0.3'
#pod 'VideoCore', path: '../..'
```

**Comment by andwun** [comment]
Yeah, also note that the version is duplicated.
I think this is what you wanted:

> pod 'VideoCore', '~>0.3'

**Comment by Craytor** [comment]
Ah, good point. So that time I was able to actually run the app, and it actually worked! So, are these warnings okay?
![screen shot 2015-10-14 at 9 56 21 am](https://cloud.githubusercontent.com/assets/3680866/10485747/dcb78b78-7259-11e5-9839-fa794f94461f.png)

**Comment by JALsnipe** [comment]
Yes, those warnings are fine.  The code is setup to support legacy SDKs.

**Comment by dourgulf** [comment]
I solved this problem by change the search path setting in Pods project. Just remove all ""${PODS_ROOT}/Headers/Private" in “Header Search Paths"

**Comment by Craytor** [comment]
So when I go to use VideoCore with a brand new project, I keep getting error about VCSessionDelegate "use of undeclared type 'VCSessionDelegate'". I have no clue what this means. I have set the project up with the Pods file, and I'm pretty sure video core is installed.
![screen shot 2015-10-14 at 11 56 47 pm](https://cloud.githubusercontent.com/assets/3680866/10504530/543da16c-72cf-11e5-8aa6-23114ab85238.png)

**Comment by Craytor** [comment]
Fixed... Don't forget to go to build settings and enter the bridging file path. This should really be in the docs.

**Comment by Craytor** [comment]
This has been solved (as mentioned way above).

**Comment by AkshayBudhiraja** [comment]
@Craytor Hey, getting the same error as you did in the last comment. Could you elaborate more on what you meant/did by entering the bridging file path? 

Thanks!

**Comment by ghost** [comment]
what's the mean of 'Don't forget to go to build settings and enter the bridging file path.'?what to do exactly?

**Comment by AgarwalMilan** [comment]
dourgulf has given the best and quickest solution to this problem.

**Comment by ZenonHuang** [comment]
@dourgulf  has given the best and quickest solution to this problem
