### ISSUE TITLE
Unable to start the RTMP session 

### ISSUE THREAD

**Issue by bintu1234** [jgh-/VideoCore#235]
@jgh- I am using video core library when i give rtmp url the below log displayed
rtmp url like rtmp://server.tv/server/userid/userid/streamID 

stream id is dynamic value

ClientState: 1
2015-12-03 11:19:59.998 app[1305:29879] ============================VCSessionStateStarting
ClientState: 2
ClientState: 3
ClientState: 4
ClientState: 5
ClientState: 6
received server window size: 10000000
received peer bandwidth limit: 10000000 type: 2
received ping, sending pong.
Received invoke
pktId: 1
received invoke _result
tracked command: connect
ClientState: 7
ClientState: 11
2015-12-03 11:20:02.046 app[1305:29879] =========================================disconnect
~RTMPSession2015-12-03 11:20:02.047 app[1305:29879] =========================================disconnect

client state are not  enter into the 8 and the stream must be flv and h264 videocodec and aac audio codec where i am missing is there any way to pass above extentions in library please help me out thanks in advance

**Comment by satyamub** [comment]
This is a issue I am also facing.. after I changed the outthink size to 1024 and then 512 and then to 128 I am getting received unknown packet type: 0x15
Help me

**Comment by satyamub** [comment]
@bintu1234 Are you using the sample broadcaster iOS code

**Comment by bintu1234** [comment]
@satyamub  yes

**Comment by satyamub** [comment]
@bintu1234 which server are you using?

**Comment by bintu1234** [comment]
Wowza server i know that you using adobe media right did you find any solution?

**Comment by satyamub** [comment]
no ... Even I am trying to configure Red5 server in local to check for the issue so that I would know there are issue in server configuration

**Comment by bintu1234** [comment]
i think that is not an a issue for the server this is because of videocore library incompatibility issue so you focus on the library is your videocore library works in xcode7.1

**Comment by satyamub** [comment]
No still i have not gone for Xcode 7.1. I am using 6.4 swift!!!Can I have your Skype?

**Comment by bintu1234** [comment]
offcourse but i am in now it is not possible to take the calls if you want you can call after 7.30

**Comment by satyamub** [comment]
Chatting here is not working thats why I am asking Skype id to ask you?

**Comment by bintu1234** [comment]
yah but in my ofc won't accept the personal media like skype ,fb,gmail sooo

**Comment by bintu1234** [comment]
@satyamub  are you using any usernames or user id in your rtmp Url

**Comment by satyamub** [comment]
Another thing is did you configure the wowza in local? if yes, can you give me steps to do it?

**Comment by bintu1234** [comment]
no at server side we configure the wowza if you want in local have a look this link https://www.wowza.com/pricing/installer download and install and configure server look this https://www.wowza.com/forums/content.php?88-How-to-configure-Apple-HTTP-Live-Streaming-packetization-(cupertinostreaming)

**Comment by bintu1234** [comment]
@satyamub  did you find any solution

**Comment by satyamub** [comment]
@bintu1234  change the pod to 0.1.12 from 0.3.2.. Now at my end with Red5 its working!!You tell me !!!

**Comment by bintu1234** [comment]
@satyamub  my problem with the rtmp url my url like rtmp://server.tv/server/userID so when i am giving user id the session is not starting i am looking for passing the dynamic data to rtmp url if any thing you know help me out

**Comment by bintu1234** [comment]
@satyamub  did your broadcast is working fine now

**Comment by satyamub** [comment]
broadcast happening after few attempt like every time its not connecting

**Comment by bintu1234** [comment]
@satyamub  did you find any thing like passing data to rtmp url

**Comment by satyamub** [comment]
@bintu1234 I am looking onto it. Please wait!!!

**Comment by satyamub** [comment]
@bintu1234  can you post the code where you are starting the RTMP!!

**Comment by bintu1234** [comment]
@satyamub  i am able to play the video now how your checking that it is broadcasting or not

**Comment by bintu1234** [comment]
@satyamub  are you able to broadcast the video

**Comment by bintu1234** [comment]
@satyamub  Are able to establish a connection with the red5 server please help me i am struck over here

**Comment by satyamub** [comment]
I have also tried communicating with Red5 however each time it was giving me error!!

**Comment by bintu1234** [comment]
@satyamub  and one more thing  how you play rtmp if its connected to the server we need to use any one player so which player you are using to broadcast the video

**Comment by satyamub** [comment]
Hi bintu1234 I tried many player however found out that some of them does not work and which works requires money so I told my website guy to convert the stream to HLS and then tried playing it

**Comment by bintu1234** [comment]
so after converting that is it playing in player? if yes which player?

**Comment by satyamub** [comment]
yes, HLS can be played through native AVPlayer or MPMoviePlayerController!!

**Comment by bintu1234** [comment]
ok are you still  using red5 server?

**Comment by satyamub** [comment]
@bintu1234..No I could make it to work, thats why shifted to Adobe FMS

**Comment by bintu1234** [comment]
but with videocore 0.1.12 its connecting right?

**Comment by satyamub** [comment]
No @bintu1234 .. it was connecting before however later I saw its not working so I shifted!!!
