### ISSUE TITLE
previewView has wrong dimensions

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [jgh-/VideoCore#246]
I'm trying to integrate VideoCore with React Native (which I intend to open source). With little knowledge with obj-c I was able to create the integration and able to stream from my react native application.
However, I didn't manage to get the previewScreen with the correct dimensions (full screen). 
![image](https://cloud.githubusercontent.com/assets/331136/11848602/7d5d9f86-a423-11e5-839d-2a5b3e64f516.png)

On the -initWithFrame I have the new session being created, and I tried to change the `previewView.frame` and `initWithVideoSize` values for all the possible values I could think of. I also created another view inside `self` to make sure it wasn't react native messing it up, but I was able to create a normal view with 100% of the size.

```obj-c
    CGRect rect = [[UIScreen mainScreen] bounds];
    
    _session = [[VCSimpleSession alloc] initWithVideoSize:rect.size frameRate:30 bitrate:1000000 useInterfaceOrientation:YES];
    _session.useAdaptiveBitrate = YES;
    _session.delegate = self;
    _session.previewView.frame = rect;

    [self addSubview:_session.previewView];

```

Does anybody has any idea?

**Comment by KCastiglione** [comment]
can you please share how to integrate with ReactJS in a gist or github thanks!

**Comment by hebbian** [comment]
There was an option `VCAspectMode` that you can set it `VCAspectModeFit` or `VCAspectModeFill`, you can see it on the old version, but I have no idea how to implement this feature on the new version.

**Comment by GuilhermeMedeiros** [comment]
I've tried FIT, FILL, Front/Back cameras. Same thing.

```obj-c
    _session = [[VCSimpleSession alloc] initWithVideoSize:rect.size frameRate:30 bitrate:1000000 useInterfaceOrientation:YES  cameraState:VCCameraStateFront aspectMode:VCAspectModeFill];
```

**Comment by GuilhermeMedeiros** [comment]
Apparently `RCTView` defaults `autoresizesSubviews` to `true`. Using the code below fixed my problem.

```obj-c
self.autoresizesSubviews = NO;
```
