### ISSUE TITLE
Preview on ReactNative works sometimes - Sample Project

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [jgh-/VideoCore#247]
I've build a separated application to demonstrated the bug with ReactNative. https://github.com/GuilhermeMedeiros/RNVideoCore

The preview is shown once in a while, and it's very common to see the error below on xcode:

`OGL(/Users/medeiros/www/RNVideoCore/ios/Pods/VideoCore/api/iOS/VCPreviewView.mm):: 253: Invalid Operation`

Could somebody give me some help?

**Comment by olivierlesnicki** [comment]
You should use the layoutSubviews hook to scale the previewView rect

**Comment by GuilhermeMedeiros** [comment]
layoutSubviews did help me, thanks.
However, I can only get the previewView to work if I instantiate the session on the init method of my view manager. If I wait for the -view method of the view manager, it's somehow "late" and the previewView doesn't get rendered properly. 
If I instantiate the view beforehand is just a waste of memory and battery :(

**Comment by GuilhermeMedeiros** [comment]
I've created a separated branch to show the proper way to implement the view initialisation with React Native, however using this method I'm not able to see the preview.
Somehow, VideoCore needs to be initialised together with the app. 

https://github.com/GuilhermeMedeiros/RNVideoCore/compare/proper-way#diff-edda675145d369ea40995787807b13f7R26

**Comment by GuilhermeMedeiros** [comment]
VideoCore cannot be instantiated more than once. I solved my problem by setting the VCSimpleSession as a static property of my class and returning it in case of defined.
I also had to implement the -didMoveToWindow (from React Native) to add the previewView to my view.  
You can follow the thread where the guys helped me on this link: https://www.facebook.com/groups/react.native.community/permalink/701162063352708/?comment_id=701244136677834&ref=notif&notif_t=group_comment

**Comment by olivierlesnicki** [comment]
@GuilhermeMedeiros have you updated your project? I was able to solve it using this:
```swift
//
//  BroadcasterView.swift
//  app
//
//  Created by Pro on 15/12/2015.
//  Copyright © 2015 Facebook. All rights reserved.
//

import Foundation
import UIKit

class BroadcasterView: UIView, VCSessionDelegate {
  
  var _session : VCSimpleSession?
  
  override func layoutSubviews() {
    super.layoutSubviews()
    
    _session = VCSimpleSession.init(
      videoSize: self.bounds.size,
      frameRate: 30,
      bitrate: 1000000,
      useInterfaceOrientation: true
    )
    
    self.insertSubview(_session!.previewView, atIndex: 0)
    
    _session!.delegate = self;
    _session!.previewView.frame = self.bounds
    
  }
  
  override func removeFromSuperview() {
    _session!.endRtmpSession()
    _session!.delegate = nil
    super.removeFromSuperview()
  }
  
  func connect() {
    switch _session!.rtmpSessionState {
    case .None, .PreviewStarted, .Ended, .Error:
      _session!.startRtmpSessionWithURL("rtmp://46.101.36.194/live", andStreamKey: "swaggaguru")
    default:
      _session!.endRtmpSession()
      break
    }
    
  }
  
  func connectionStatusChanged(sessionState: VCSessionState) {
    
  }
  
}

```

**Comment by GuilhermeMedeiros** [comment]
layoutSubviews is called many many times. You don't want to add subviews all the time.

**Comment by olivierlesnicki** [comment]
Have you updated your repo with a working version then?

**Comment by GuilhermeMedeiros** [comment]
Yes: https://github.com/GuilhermeMedeiros/RNVideoCore/tree/proper-way
It's gonna be a work in progress for quite some time, but that version already works.
