### ISSUE TITLE
front camera is flipped compared to the native camera

### ISSUE THREAD

**Issue by peiweichen** [jgh-/VideoCore#281]

**Comment by peiweichen** [comment]
*_VideoCore camera:
*_![3 pic_thumb](https://cloud.githubusercontent.com/assets/6760710/13658562/439f88b8-e6b3-11e5-8c7a-f1b52098a1e1.jpg)

*_The native camera
*_![2 pic_thumb](https://cloud.githubusercontent.com/assets/6760710/13658558/34ce0bac-e6b3-11e5-96c3-141e663bee1b.jpg)

**Comment by JALsnipe** [comment]
Duplicate of #112.
