### ISSUE TITLE
Method captureOutput didOutputSampleBuffer: fromConnection: randomly doesn't work

### ISSUE THREAD

**Issue by SonnyBlack** [jgh-/VideoCore#290]
My colleague noticed that on his device instead video capturing randomly appear black screen. After some investigation I figure out that in file CameraSource.mm method 

`- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection
`
sometimes just doesn't working.

I looked on many video session creation examples - I didn't find any fundamental differences between them, so I can't understand why this issue appears. I checked different errors - for example on:

`input = [AVCaptureDeviceInput deviceInputWithDevice:((AVCaptureDevice*)m_captureDevice) error:&inputError];`

There are no errors.

Any ideas/suggestion?

Thanks in advance.

**Comment by MikeDonahue** [comment]
@SonnyBlack I recently noticed this happening on 6 and 6s plus devices as well.

**Comment by SonnyBlack** [comment]
Finally I have found reason. If you use 
`[output setSampleBufferDelegate: queue:]`
multiple times, be careful.

In my case I have 2 view controllers (further - VC): one with my video session, second with Video Core session. From 1st VC app perform transition to second. As result, in 1st VC session destroyed later (after creating Video Core session in second VC). Although app used different queues, in my case they bind to system AVFoundation queue, so it looks like using of shared resource.
