### ISSUE TITLE
VCPreviewView.mm : 236: Invalid Operation 

### ISSUE THREAD

**Issue by ghost** [jgh-/VideoCore#329]
I am using https://github.com/yuyedaidao/pili-ios-camera-recorder library to stream video using RTMP. The library uses VideoCore in it. In my app right after I stop streaming I get  `OGL(/Users/ravi/repo/LiveStreaming/PLRecorderKit/Vendor/VideoCore/api/iOS/VCPreviewView.mm):: 236: Invalid Operation`

in Log. The log continues to print as long as the app is running.

**Comment by bintu1234** [comment]
Did you find any solution

**Comment by ghost** [comment]
Yes, this was because we did a mistake. We were setting the preview window value to nil.
