### ISSUE TITLE
Stability of RTMP Session

### ISSUE THREAD

**Issue by usman3d** [jgh-/VideoCore#33]
Hi,

I have observed that VideoCore occasionally terminates the session because it receives kStreamEnd status .(RTMP status 11 is also often printed in the log before termination ). 
How to reproduce?
When I run the recording session for longer time (such as 30+ or 40+ minutes), then recording session often terminates without giving any meaningful warning. 

I believe this issue occurs because of:
1- Poor wifi connection 
In this case we don't get meaningful warning, just RTMP status number 11, and then termination
2- Memory leaks
I believe memory leaks cause the crash of the recording session/app. At crash it shows me the call stack : parseCurrentData() -> handleInvoke() -> get_string() But I'm not sure if this is the exact part of code that is causing memory leak.

Can others verify if these issues can be reproduced at their end?

Thanks.

**Comment by chinnuios** [comment]
@usman3d  Hi, Did you solved issue ? if yes, please tell me
