### ISSUE TITLE
Using rear facing camera

### ISSUE THREAD

**Issue by Mark117** [jgh-/VideoCore#48]
Heya, just wondering how would I select the rear facing camera for streaming?

I see this method: CameraSource::setupCamera(int fps, bool useFront) and i've tried changing the boolean useFront to false (void setupCamera(int fps = 15, bool useFront = true)) in the CameraSource.h but it still doesn't change the camera source.

Would you have any idea why this is not working?

Thank you,

Mark

**Comment by loretoparisi** [comment]
For me it worked on the master with

```
-(IBAction)toggleCamera:(id)sender {
    VCCameraState cameraState;
    cameraState = [_session cameraState];
    VCCameraState newCameraState = (cameraState == VCCameraStateBack) ? VCCameraStateFront : VCCameraStateBack;
    NSString *cameraStateStr = (cameraState == VCCameraStateBack) ? @"Front" : @"Read";
    [self.btnCamera setTitle:cameraStateStr forState:UIControlStateNormal];
    [_session setCameraState:newCameraState];
}
```

**Comment by HarishSami** [comment]
I am using videoCore 2.0.
when i am using the front camera the preview is showing the opposite direction?
i searched a lot?i can't find any solution?
