### ISSUE TITLE
RTMP Connection doesn't continue 

### ISSUE THREAD

**Issue by laylash** [jgh-/VideoCore#50]
I tested the broadcaster with both red5 server and a python rtmp server, but am getting the following on the default values:

Context creation succeeded
RTMPStatus: 1
RTMPStatus: 2
RTMPStatus: 3
RTMPStatus: 4
RTMPStatus: 5
RTMPStatus: 6
## received server bandwidth

Changing frame rate to 15 and bandwidth to 65000 gives the following result:
Context creation succeeded
RTMPStatus: 1
RTMPStatus: 2
RTMPStatus: 3
RTMPStatus: 4
RTMPStatus: 5
RTMPStatus: 6
received server bandwidth
received invoke _result
tracked command: connect
RTMPStatus: 7
received unknown packet type: 0x00
received invoke _result
## tracked command: releaseStream

What can be wrong and should i change frame rate and bandwidth to other values?? or the problem is from the server??

**Comment by pkir** [comment]
I am still getting the same issue with EvoStream:
2015-04-07 16:32:30.753 SampleBroadcaster[210:6162] Creating context
2015-04-07 16:32:30.791 SampleBroadcaster[210:6162] Context creation succeeded
ClientState: 1
ClientState: 2
ClientState: 3
ClientState: 4
ClientState: 5
ClientState: 6
received server window size: 1048576
received peer bandwidth limit: 2500000 type: 2
received ping, sending pong.
Received invoke
pktId: 1
received invoke _result
tracked command: connect
ClientState: 7
received unknown packet type: 0x1E
Received invoke
pktId: 2
received invoke _result
tracked command: releaseStream
received unknown packet type: 0x00
