### ISSUE TITLE
Need to integrate this broadcasting in my existing iOS application with xib.

### ISSUE THREAD

**Issue by vaibhavTesting** [jgh-/VideoCore#51]
Hi Support Team,

I need to add this video broadcasting feature in my  existing application with xib, So when I import ViewController.h file in any class..getting error like: -
'cstdlib' file not found...

Please help me out..or please suggest how can I navigate from my view controller to ViewController.mm..in xib project..

Thanks,
Vaibhav

**Comment by ravigautam7786** [comment]
Vabhav,

I am also integrating this library into my existing code and i am having the same error.

Please help me.

Thanks
Ravi
