### ISSUE TITLE
Audio is not audible when using VideoCore

### ISSUE THREAD

**Issue by PrabakarMP** [jgh-/VideoCore#65]
Hi,

I've integrated VideoCore into my iPad project and trying to implement live video chat. I am using Wowza streaming server. I am streaming live video from my iPad project to Wowza, it works nice with the help of VideoCore. Thanks a lot to the VideoCore developers. Now, As I said its like live video chat, I have added an another view in my iPad project and MPMoviePlayerController added into it. And I am using "Flash Media Live Encoder" to stream desktop cam video to Wowza streaming engine, It works very fine either. And then, that Wowza mobile live streaming link has given in my iPad MPMoviePlayer view to see the live streaming video from desktop to iOS. It is streaming fine. But, when I talk something on the desktop side to check the audio, it doesn't produces the audio loudly, instead very little sound it produces. The same desktop live recorded video is properly and exactly streamed to Wowza without any issues.

Then, I removed initializing below VideoCore line of code in my iPad project, JUST for testing the audio issue,
_session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(1290, 800) frameRate:30 bitrate:1000000 ];

Then the Audio is coming loudly and properly as expected.

I confirmed that initializing VCSimpleSession is doing something to make this audio not working properly, when  MPMoviePlayerController added  and used for displaying desktop live video streaming.

Could you experts advise me, what should i do in this case? Why initializing VCSimpleSession creating audio not audible issue on the MPMoviePlayerController added  and used for displaying desktop live video streaming in the iPad app.

**Comment by yycc** [comment]
@jgh-   I've integrated VideoCore into my project for live video chat. I used acd.componentSubType = kAudioUnitSubType_VoiceProcessingIO  instead of acd.componentSubType = kAudioUnitSubType_RemoteIO. If I just playing or recording video, it work excepted . when I playing and recording at the same time. I found that  the voice is very low. can you give me any suggest to solve this problem.Thank you very much😊.
