### ISSUE TITLE
Red5 Server related issue (received unknown packet type: 0x00)

### ISSUE THREAD

**Issue by trident10** [jgh-/VideoCore#67]
Hi

I used the 0.1.12 version and I am using red5 server for rtmp. When I run the sample application, I get the following result on console :- 

creation succeeded
ClientState: 1
ClientState: 2
ClientState: 3
ClientState: 4
ClientState: 5
ClientState: 6
received server window size: 10000000
received peer bandwidth limit: 10000000 type: 2
Received invoke
pktId: 2147483647
received invoke onBWCheck
received peer bandwidth limit: 67 type: 0
received unknown packet type: 0x00

I am sorry, I am new to RTMP protocol but what I found regarding this is that it is basically a ping code of control stream and 0x00 denotes control of clear stream. (Found this http://www.gnu.org/software/gnash/manual/doxygen/namespacegnash_1_1rtmp.html#af251a68160f778916349436ca7398bb2).

I really don't know. I might be wrong but can you suggest me what needs to be done so that I can move ahead.

Thanks 
Abhimanyu

**Comment by cocoajin** [comment]
I use the  ngix-rtmp server, work fine.
That is  a  bug of red5 server.
https://github.com/arut/nginx-rtmp-module

**Comment by satyamub** [comment]
@abhimanyujindal10 what is the cocoapod version of video core you are using because I am using the 0.1.12 of videocore and Red5 1.0.3 still its not working!!!

**Comment by chinnuios** [comment]
@cocoajin  HI, Actually, I don not konw .How to add ngix-rtmp server into project .please give me instruction ??
