### ISSUE TITLE
Tried updating demo app to 0.2 and video is blank

### ISSUE THREAD

**Issue by dhilowitz** [jgh-/VideoCore#92]
Hi,

I tried updating the sample broadcast app to 0.2.1 and the video preview was blank. Is there something I need to change in order to get this to work?

Thanks,
Dave

**Comment by JALsnipe** [comment]
@maxcampolo Does your session work on a 4s for you if you try to change the `cameraState` or init like this?

```
_session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(1280, 720) frameRate:30 bitrate:1000000 useInterfaceOrientation:YES cameraState:VCCameraStateFront];
```

**Comment by maxcampolo** [comment]
@JALsnipe yes with the most recent release
