### ISSUE TITLE
Cannot change Camera State on iPhone 4s

### ISSUE THREAD

**Issue by JALsnipe** [jgh-/VideoCore#94]
I cannot use the init method with `cameraState` or change the `camreaState` value at all on a 4s device.

Ways to reproduce:
1.
```
- (void)viewDidLoad {
    [super viewDidLoad];
    _session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(480, 480) frameRate:30 bitrate:1000000 useInterfaceOrientation:YES cameraState:VCCameraStateFront];
    _session.previewView.frame = self.previewView.bounds;
    _session.delegate = self;
}
```
Preview view shows black screen, nothing else.

2.
```
- (void)viewDidLoad {
    [super viewDidLoad];
    _session = [[VCSimpleSession alloc] initWithVideoSize:CGSizeMake(480, 480) frameRate:30 bitrate:1000000 useInterfaceOrientation:YES];
    
    [self.previewView addSubview:_session.previewView];
    _session.previewView.frame = self.previewView.bounds;
    _session.delegate = self;
}

// ...

- (IBAction)changeCamera:(id)sender
{
    switch (_session.cameraState) {
        case VCCameraStateFront:
            _session.cameraState = VCCameraStateBack;
            break;
            
        case VCCameraStateBack:
            _session.cameraState = VCCameraStateFront;
            break;
            
        default:
            break;
    }
}
```
Session starts fine using the front facing camera.  When I try to switch the camera using the `changeCamera` method above, the UI freezes.

Device info:
iPhone 4s 16gb model running 8.1.2 (12B440)

Let me know if you need any more information.

Thanks.

**Comment by JALsnipe** [comment]
Any updates on this?  This is also reproducible in the sample app.

**Comment by jgh-** [comment]
I haven't had the opportunity to give it a test since I don't have any device like the 4s.  Can you run the program in the debugger, and when it freezes press the Pause button and then type "bt all" in the lldb console and paste the resulting stack trace to a gist?

**Comment by JALsnipe** [comment]
Here's the backtrace:
https://gist.github.com/JALsnipe/1577094029661130eb3a

I also found another 4s running 8.0.2.  Surprisingly, the camera switched fine on that device:
https://gist.github.com/JALsnipe/f6215ccbc54e4dd37210

I have a third 4s device I am upgrading to 8.1.2 now to test again.  I'm wondering if this weird bug is device-specific, or versions specific.

Thanks again for all of your help.

**Comment by JALsnipe** [comment]
Confirming that this may be a device-specific issue.  When I tried the sample project on a third 4s with 8.1.2, the camera was switching fine:
https://gist.github.com/JALsnipe/184d10fbf718d8910d40

**Comment by jgh-** [comment]
Hm, try the latest commit I made - I changed the toggle method a bit.

**Comment by JALsnipe** [comment]
Doesn't appear to have changed anything:
https://gist.github.com/JALsnipe/19bf293ab2d5e7de6686

I don't know why this could be happening.  Both of the device's cameras function fine.  At least it isn't a complete blocker since I haven't been able to produce it on other 4s devices.

**Comment by JALsnipe** [comment]
Going to close this, pretty sure this was a device-specific defect.  If anyone has a similar issue I'd be happy to reopen and help them.
