### ISSUE TITLE
Crash when app goes background

### ISSUE THREAD

**Issue by havocked** [jgh-/VideoCore#97]
Hi there is a crash when the app goes background (IOS 8)

at this line in the method : - (void) drawFrame:(CVPixelBufferRef)pixelBuffer (VCPreviewView.mm)

[self.context presentRenderbuffer:GL_RENDERBUFFER];

**Comment by JALsnipe** [comment]
This should be fixed in the 0.2.0 release.  Make sure you're using the latest version (0.2.1.3).  Also, this issue was already addressed in #83: https://github.com/jgh-/VideoCore/issues/83

**Comment by jgh-** [comment]
hi @havocked have you updated to the latest version and given it another try?

**Comment by havocked** [comment]
Hi !

I've just updated to your version, I keep you in touch at the end of the other week after a few tests ! Sorry for the late response.

By the way one question:

Is it for purpose that there is not a public access on the AVCaptureSession ?
I see that you allocated it in CameraSource.mm so no way to get a ref back in the project code. :(

Just asking that because using your library shrinks the liberty of manipulating the camera (for e.g.: turn off the camera when view disappear), Or did I miss a method that can do that ?

But still, thank you so much for your great library ! Once I really understand the architecture, I will try to send some improvements !

**Comment by havocked** [comment]
Hi again,

Si after many tries, it seems to be more stable but still there are stuff that can be really frustrating to being able to control ^^

Such as, VCSimpleSession *session <- how can i stop it entirely ? after endrtmpsession, no way I can stop it ! If I put it at nil -> crash.

Is there a way you can give some example of use ? (also with filters !)

That would be really great ! Thanks again !

NOTE: also it seems that there are still some depreciated methods in the lib:
![screen shot 2015-02-05 at 18 59 39](https://cloud.githubusercontent.com/assets/7999585/6065909/2aa0b3d4-ad69-11e4-9107-314fed2e97c3.png)

**Comment by jgh-** [comment]
hi @havocked - The deprecations are there because VideoCore is actually compatible with iOS 6 (and potentially 5 but I have no means of testing iOS 5), those functions aren't called if you're using iOS 7 or higher.

As for the crash, can you post a backtrace gist of that crash?  You need to make sure you remove the preview view from its superview before destroying the VCSimpleSession.  Destroying the session will also end the RTMP session automatically, so you don't have to call endRtmpSession first.

**Comment by JALsnipe** [comment]
I've seen this crash too.  Just make sure that you're not deallocating the session when the app goes to the background.  There's a race condition where the session may not dealloc completely when receiving the `applicationDidEnterBackground` notification, causing GL calls to be run while the app is backgrounded, causing the crash.

**Comment by havocked** [comment]
Hi,

I managed to delete my session whenever I want without a crash !

if (_session) {
        didAddCameraSource = NO;
        for (UIGestureRecognizer *recognizer in _session.previewView.gestureRecognizers) {
            [_session.previewView removeGestureRecognizer:recognizer];
        }
        [_session.previewView removeFromSuperview];
        _session = nil;
    }

Thanks again !

**Comment by araii** [comment]
hm
